### ISSUE TITLE
请问,其他的公钥文件怎么转成你那种数组

### ISSUE THREAD

**Issue by Y-A-K-E** [terrantsh/RSA2048#3]
比如
```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDFb9hpuMWvJP/809dgCi4J6G7T
M85dHNM4QBFf3tPzo0fVpvkcSN+jnEM9UuZlCX3yRNaMKkHQ3ls8eqcxmDq97+1j
4BkL+0I4XUMv3BXp2M3fRZmpTpsACXCmRvy9njtoO7ZG5aETRKclgst5lU3sagPc
iUVZkAi50AO4QhrgQwIDAQAB
-----END PUBLIC KEY-----```

**Comment by terrantsh** [comment]
网上有小工具，您可以搜索一下，稍晚些发给您



---原始邮件---
发件人: "Y.A.K.E"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 下午3:26
收件人: "terrantsh/RSA2048"<RSA2048@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [terrantsh/RSA2048] 请问,其他的公钥文件怎么转成你那种数组 (#3)




 
比如
 -----BEGIN PUBLIC KEY----- MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDFb9hpuMWvJP/809dgCi4J6G7T M85dHNM4QBFf3tPzo0fVpvkcSN+jnEM9UuZlCX3yRNaMKkHQ3ls8eqcxmDq97+1j 4BkL+0I4XUMv3BXp2M3fRZmpTpsACXCmRvy9njtoO7ZG5aETRKclgst5lU3sagPc iUVZkAi50AO4QhrgQwIDAQAB -----END PUBLIC KEY-----```

**Comment by Tommy0607** [comment]
同问，现在发了没

**Comment by Y-A-K-E** [comment]
> 
> 
> 同问，现在发了没

理论上只需要MI....开始不包括begin和end标记的核心内容部分.
base解密之后,十六进制就是.
